Mad/allow payload for post requests
teamshares/teamshares-rails pull request #303
Opened 2023-09-27 21:39 UTC by CrookedGrin

## Ticket
[EOYT: Services for Address Validation](https://www.notion.so/teamshares/EOYT-Services-for-Address-Validation-44bf79f0225c4b1db70da2b1217ce3e7?pvs=4)

## Description
The generic HTTP client did not previously allow for passing an actual payload in a POST request. This fixes that. Note that the second parameter passed to `connection.send` should always be `nil` as opposed to `payload`, which is actually the 3rd parameter. This was misleading as written previously.

## Release Reminder (check before submitting PR)
- [] I remember this is a _public_ repository (don't commit anything confidential)
- [] I'm aware I'll need to push PRs to any consuming apps that need to _use_ these changes (`bundle update --conservative teamshares_rails`)

2023-09-27 22:11 UTC, nilesmc commented on README.md
> +4. If you're on a branch of `teamshares-rails` other than `main`, you will see an error in the console that your Gemfile is expecting to install from `main`. You can change that in your local `Gemfil
Helpful 👍🏻

2023-09-27 22:12 UTC, nilesmc approved these changes
Boom, love the expansion of functionality along w maintaining tight simple statements.

2023-09-29 17:50 UTC, kdonovan requested changes
Unfortunately [the faraday docs](https://lostisland.github.io/faraday/#/getting-started/quick-start?id=get-head-delete-trace) imply POST requests send data as the _second_ argument (the third is for headers), so we may need to bifurcate the calls rather than just `send` GETs and POSTs identically. 🤔  (@nilesmc , thoughts?)

2023-09-29 17:52 UTC, CrookedGrin commented
> Unfortunately [the faraday docs](https://lostisland.github.io/faraday/#/getting-started/quick-start?id=get-head-delete-trace) imply POST requests send data as the _second_ argument (the third is for headers), so we may need to bifurcate the calls rather than just `send` GETs and POSTs identically. 🤔 (@nilesmc , thoughts?)

Yeah, I found the docs a bit confusing, but I've tested this against an actual API (the Google Address Validation API, to be specific) and it works. So maybe the docs are wrong / misleading?

2023-09-29 18:01 UTC, nilesmc commented
> Unfortunately [the faraday docs](https://lostisland.github.io/faraday/#/getting-started/quick-start?id=get-head-delete-trace) imply POST requests send data as the _second_ argument (the third is for headers), so we may need to bifurcate the calls rather than just `send` GETs and POSTs identically. 🤔 (@nilesmc , thoughts?)

It's a little confusing as we are using send for the request type.

*  First is request method type
*  Second arg is actually the first arg (url). 
*  Third is body or param. 
*  Fourth could be headers.

Since we are all ready setting the url above, we dont need to reset it. Nil would actually be the place where we would set the url (but we dont need to).

`@response = connection.send(type, nil, payload)`

I am pretty sure this is correct.

2023-09-29 18:29 UTC, CrookedGrin commented on lib/ts/client/generic_base_client.rb
> +    # The Faraday docs refer to using `get` and `post` directly.
@nilesmc @kdonovan Added some clarifying comments here for the next poor fool to come along

2023-09-29 18:56 UTC, CrookedGrin commented on lib/ts/client/generic_base_client.rb
>    def call(connection, type, payload: nil)
@nilesmc @kdonovan Added some clarifying comments here for the next poor fool to come along

2023-09-29 20:49 UTC, kdonovan approved these changes
@nilesmc @CrookedGrin thanks for the clarifications! Love Niles' idea of smoke testing, but that was my only concern. 🚗

2023-10-02 18:22 UTC, nilesmc commented
Using this branch locally, I was able to close a Lead in Buyout, and trigger a webhook to OS, then a get to Buyout from os...

After the whole Rube-Goldberg machine did its thing, it created a company in OS: 

![Screenshot 2023-10-02 at 11 13 17 AM](https://github.com/teamshares/teamshares-rails/assets/4657767/3b11afe9-4315-4ede-8ae5-4e04ab78c822)

TLDR; We are good to merge!

2023-10-02 18:46 UTC, merged